theme: minima
title: Sturban is awesome
author: sturban
email: sturban@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the description
  more to describe
  
# social links
twitter_username: sturban # DO NOT include the @ character, or else the build will fail!
github_username:  sturban # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
